version: '3.8'


networks:
  prod:


services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    networks:
      - prod
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=shop
    networks:
      - prod

volumes:
  postgres_data:

